create table T_PARTY_DRINK_ATTEND (
    ID integer generated by default as identity,
    MEMBER_NUM integer not null,
    PARTY_NUM integer not null,
    PARTY_ATTEND_FLRAG integer not null,
    constraint T_PARTY_DRINK_ATTEND_PK primary key(ID)
);
