create table MEMBER (
    ID integer generated by default as identity,
    NAME varchar(255),
    HNAME varchar(255),
    SEX integer not null,
    MAIL integer,
    DEPARTMENT integer,
    CURRICULUM integer not null,
    ENTRANCE integer not null,
    GRADE integer not null,
    TEL1 integer not null,
    TEL2 integer not null,
    TEL3 integer not null,
    OFFICER integer not null,
    USER_NAME integer,
    PASSWORD integer,
    constraint MEMBER_PK primary key(ID)
);
